 <?php
 // module/Application2/view/application2/application2/delete.phtml:

 $title = 'Supprimer une personne';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Vous &ecirc;tes sur de vouloir supprimer 
     '<?php echo $this->escapeHtml($application2->prenom); ?> <?php echo $this->escapeHtml($application2->nom); ?>' de la base ?
 </p>
 <?php
 $url = $this->url('application2', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $application2->id; ?>" />
     <input type="submit" name="del" value="Oui" />
     <input type="submit" name="del" value="Non" />
 </div>
 </form>
 