<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script>

	function annuleModif (lib) {
        alert('test');
		$.ajax({
			url      : 'http://localhost:82/Zend2/public/application2/modif/'+lib,
			dataType : 'json',
			success  : function (data) {       

			}
		});
	}

</script> 




<?php
 // module/Application2/view/application2/application2/edit.phtml:

 $title = 'Ajouter/Modifier une note';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>


 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'application2',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nom'));
 echo $this->formRow($form->get('prenom'));
 echo $this->formRow($form->get('note'));
 echo $this->formRow($form->get('exercices'));
 
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 ?>

 <a onClick="annuleModif (<?php echo $this->id?>);" href="">Annuler les Modifications apporter</a>
