<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script>

    function supprime (etudiant) {
        if (confirm('Vous etes sur de vouloir supprimer cet etudiant de la BASE?')) {
			alert('Votre etudiant a ete supprime de la BASE');
			$.ajax({
				url      : document.location.protocol + '//localhost:82/Zend2/public/application2/supp/'+etudiant,
				dataType : 'json',
				success  : function (data) {                
					alert("sucess");

				}
			});
		}	 
	}
//Appel AJAX:
//$(document).ready(supprime ());



</script> 
 
 
 <?php
 
 $title = 'My application2';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('application2', array('action'=>'add'));?>">Ajouter un nouveau etudiant</a>
 </p>

 <table class="table">
 <tr>
     <th>Prenom</th>
     <th>Nom</th>
     <th>Note </th>
     <th>Exercices </th>
	 <th>Fonctions</th>
 </tr>
 <?php foreach ($application2s as $application2) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($application2->prenom);?></td>
     <td><?php echo $this->escapeHtml($application2->nom);?></td>
	 <td><?php echo $this->escapeHtml($application2->note);?></td>
	 <td><?php echo $this->escapeHtml($application2->exercices);?></td>
	 
     <td>
         <a href="<?php echo $this->url('application2',
             array('action'=>'edit', 'id' => $application2->id));?>">Ajouter/Modifier une Note</a><br>
         <a href="<?php echo $this->url('application2',
             array('action'=>'delete', 'id' => $application2->id));?>">Supprimer Personne</a><br>
		 <a onClick="supprime(<?php echo $application2->id?>);" href="">Supprimer en JSON</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 
 

